### PR TITLE
Handle files when external linker was used.

### LINKED ISSUE #76: gosym can provide the wrong address for funcs in cgo go binary
As described in https://github.com/golang/go/issues/65232, `gosym.NewLineTable` should be used with the value of symbol `runtime.text` but not just use the start of `.text` segment, which was used by gore right now.

I have no idea how to implement a search for `runtime.text` in the stripped binary, but at least we can show a warning like `the offset in func can be incorrect in cgo binary` right now.

image

### PR DESCRIPTION
**Pull request by TcM1911**
This adds logic that gets the runtime.text value from the moduledata structure, and uses it to parse the pclntab. This ensures that the function address are correct since the runtime.text is used as the base address by the runtime.

Additionally, ELF files compiled as PIE files, does not have a specific section for the pclntab. So a fallback logic has been added to search for the table that is similar to what is used for PE files.

Closes: #76 and #79

This is an alternative solution to #89 that doesn't use symbols.

### CODE REVIEW

File: file.go [hunk 1]
```diff
@@ -130,6 +130,10 @@ type GoFile struct {
 	initPackagesOnce  sync.Once
 	initPackagesError error
 
+	runtimeText  uint64
+	pclntabAddr  uint64
+	pclntabBytes []byte
+
```
Comment (Zxilly) [inline file.go]: I think it's much better to add a `sync.Once` to prevent the race condition. Also, the error we met should also be cached.

**Review by Zxilly — CHANGES_REQUESTED** [review]
Others lgtm

**Review by Zxilly — APPROVED** [review]
lgtm, I will add symbol support based on this later.
