### PR TITLE
fix: corretly generate goversions

### LINKED ISSUE #87: Generate of moduledata timeout
The daily cron job is currently timing out after 6 hours. It appears to be due to the moduledata code generation. It has currently been [disabled](https://github.com/goretk/gore/commit/d54afa1d0f55434685ad7254b9e369ed6ec01e4c). 

https://github.com/goretk/gore/actions/runs/7862718547
```
Run go generate ./...
go: downloading github.com/google/go-github/v58 v58.0.0
go: downloading golang.org/x/mod v0.14.0
go: downloading golang.org/x/arch v0.6.0
go: downloading github.com/google/go-querystring v1.1.0
Error when parsing time: parsing time "date" as "2006-01-02T15:04:05Z07:00": cannot parse "date" as "2006"
Error when parsing time: parsing time "date" as "2006-01-02T15:04:05Z07:00": cannot parse "date" as "2006"
Error when parsing time: parsing time "date" as "2006-01-02T15:04:05Z07:00": cannot parse "date" as "2006"
Error when parsing time: parsing time "date" as "2006-01-02T15:04:05Z07:00": cannot parse "date" as "2006"
Error when parsing time: parsing time "date" as "2006-01-02T15:04:05Z07:00": cannot parse "date" as "2006"
/home/runner/work/gore/gore/goversion_gen.go changes detected.
Fetching moduledata for go1.5...
Fetching moduledata for go1.6...
Fetching moduledata for go1.7...
Fetching moduledata for go1.8...
Fetching moduledata for go1.9...
Fetching moduledata for go1.10...
Fetching moduledata for go1.11...
Fetching moduledata for go1.12...
Fetching moduledata for go1.13...
Fetching moduledata for go1.14...
Fetching moduledata for go1.15...
Fetching moduledata for go1.16...
Fetching moduledata for go1.17...
Fetching moduledata for go1.18...
Fetching moduledata for go1.19...
Fetching moduledata for go1.20...
Fetching moduledata for go1.21...
Fetching moduledata for go1.22...
Error: The operation was canceled.
```

### PR DESCRIPTION
**Pull request by Zxilly**
Closes: #87 

csv header was removed in the rewritten version of golang-versions generator.
When I resolved the conflict in https://github.com/goretk/gore/pull/77, I didn't notice that the https://github.com/goretk/gore/commit/b4737e6e3c166821351b7b1155d11d616ce7dd0b was generated by the old generation code. This patch migrates the old style data to the latest.

### CODE REVIEW

**Comment by Zxilly** [comment]
Seems some other error exists.

**Comment by Zxilly** [comment]
@TcM1911 The old implementation will get into deadlock when some of the request failed and throw an error. This patch fixes it.

**Comment by Zxilly** [comment]
I think it might be an error on rate limiting of GitHub REST API. So I also add a check mechanism to prevent duplicate requests.

**Comment by TcM1911** [comment]
That make sense. I poked around a bit and it looks like the issue is around generating the std packages. We are hitting the API pretty hard so maybe we should just do a git clone of the go source and walk the folder instead. What do you think of that as an approach?

**Comment by Zxilly** [comment]
I think it's possible. I will try to implement it with git cat-file or something.

**Comment by TcM1911** [comment]
I can merge this for now.

**Comment by Zxilly** [comment]
I'd like to stick with this PR, my local branch is a bit of a mess

**Comment by TcM1911** [comment]
Sounds fine. Let me know when it is ready to be merged.

**Comment by Zxilly** [comment]
@TcM1911 I think it's ready for review.

File: gen/repo.go [hunk 1]
```diff
@@ -0,0 +1,90 @@
+package main
+
+import (
+	"errors"
+	"fmt"
+	"os"
+	"os/exec"
+)
+import "github.com/go-git/go-git/v5"
```
Comment (TcM1911) [inline gen/repo.go]: Run gofmt on the file to fix the import section.

File: gen/repo.go [hunk 2]
```diff
@@ -0,0 +1,90 @@
+package main
```
Comment (TcM1911) [inline gen/repo.go:18]: Copy right and license statement

**Review by TcM1911 — CHANGES_REQUESTED** [review]
Minor things to fix before merge.

File: gen/repo.go [hunk 3]
```diff
@@ -0,0 +1,125 @@
...
+
+	goRepo = repo
+
+	return nil
+}
+
+func cloneRepo(goRepoDir string) error {
+	fmt.Println("cloning repo")
+	// Since golang codebase is a huge repo, clone it with go implementation is extremely slow
+	cmd := exec.Command("git",
```
Comment (TcM1911) [inline gen/repo.go:59]: Since the checkout is now performed in the workflow, this can be removed.

Comment (Zxilly) [reply gen/repo.go:59]: This was used for developers in case they needed to generate code locally. Also used as a fallback for retrieving a corrupted repo with a bad network connection.

**Comment by TcM1911** [comment]
Good run https://github.com/goretk/gore/actions/runs/7890574561/job/21533033013
